name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 25

      - run: npm ci
      - run: npx @11ty/eleventy --output=_site

      - name: Push preview branch
        id: preview
        run: |

          if [ "$GITHUB_EVENT_NAME" = "push" ] && [ "$GITHUB_REF" = "refs/heads/main" ]; then
            BUILD_BRANCH="site"
            COMMIT_MESSAGE="Build ${{ github.sha }}"
          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BUILD_BRANCH="preview/site"
            COMMIT_MESSAGE="Build ${{ github.event.pull_request.head.sha }}, \
                            PR #${{ github.event.pull_request.number }}"
          else
            exit 0
          fi

          rm -rf node_modules
          mv _site /tmp/site

          git config user.email "ci@github"
          git config user.name "GitHub CI"

          git fetch origin
          git switch $BUILD_BRANCH || git switch --orphan $BUILD_BRANCH

          cp -r /tmp/site/* .

          git add .
          git commit -m "$COMMIT_MESSAGE" || exit 0
          git push origin $BUILD_BRANCH

          echo "preview_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Comment
        if: ${{ github.event_name == 'pull_request' && steps.preview.outputs.preview_sha }}
        run: |

          PREVIEW="../blob/${{ steps.preview.outputs.preview_sha }}/index.html"

          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "Preview: [${{ steps.preview.outputs.preview_sha }}]($PREVIEW)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
